spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/barber}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
  servlet:
    context-path: /manager-barbershop

security:
  jwt:
    secret: ${JWT_SECRET:afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf}
    expirationTime: ${JWT_EXPIRATION_TIME:2}